language: php

php:
    - 5.3.3
    - 5.3
    - 5.4

before_script:
    - mysql -e 'CREATE DATABASE dbal_test'
    - psql -c 'CREATE DATABASE dbal_test' -U postgres

    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

script: phpunit --configuration phpunit.travis.xml

notifications:
    email:
        - geloen.eric@gmail.com
