language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - PHPUNIT_CONFIG=phpunit.xml.dist
    - PHPUNIT_CONFIG=phpunit.travis.xml

before_script:
    - composer self-update
    - composer install --prefer-source

script:
    - bin/phpunit --configuration $PHPUNIT_CONFIG

notifications:
    email: geloen.eric@gmail.com
