language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

before_script: composer install --dev
script: bin/phpunit --configuration phpunit.travis.xml

notifications:
    email: geloen.eric@gmail.com
